version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - terraform --version
      - aws --version
  build:
    commands:
      - echo "Deploying Infrastructure..."
      - cd terraform
      - terraform init -input=false
      - terraform apply -auto-approve -input=false
  post_build:
    commands:
      - echo "Infrastructure Live. Updating Access..."
      - aws eks update-kubeconfig --name prod-eks --region us-east-1
      - echo "Verifying ArgoCD and Secrets Operator..."
      - kubectl get pods -n argocd
      - kubectl get pods -n external-secrets