apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  annotations:
    # This annotation connects the K8s user to the AWS IAM Role
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      serviceAccountName: app-service-account
      containers:
      - name: api
        image: ghcr.io/stefanprodan/podinfo:latest
        env:
        - name: REDIS_URL
          value: "redis-service:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets # Matches the ExternalSecret target name
              key: password
        # Health Checks
        readinessProbe:
          httpGet: { path: /readyz, port: 9898 }
          initialDelaySeconds: 10
        livenessProbe:
          httpGet: { path: /healthz, port: 9898 }